name: Deploy Node.js to aaPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: SSH Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AAPANEL_HOST }}
          username: ${{ secrets.AAPANEL_USERNAME }}
          password: ${{ secrets.AAPANEL_SSH_KEY }}
          script: |
            cd /www/wwwroot/geo
            git pull origin main
            npm install --production
            pm2 restart my-backend
